[project]
name = "dorst-printer"
version = "1.0.0"
description = ""
dependencies = [
    "flask",
    "requests",
    "python-escpos",
    "waitress",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"